export const SET_ALERT = 'SET_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const SET_TOAST = 'SET_TOAST';
export const CLEAR_TOAST = 'CLEAR_TOAST';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const ADD_QUESTIONS = 'ADD_QUESTIONS';
export const LOADING_QUESTIONS = 'LOADING_QUESTIONS';
export const CLEAR_QUESTIONS = 'CLEAR_QUESTIONS';
export const FETCH_QUESTIONS_ERROR = 'FETCH_QUESTIONS_ERROR';

export const ADD_QUESTIONS_SEARCH = 'ADD_QUESTIONS_SEARCH';
export const LOADING_QUESTIONS_SEARCH = 'LOADING_QUESTIONS_SEARCH';
export const CLEAR_QUESTIONS_SEARCH = 'CLEAR_QUESTIONS_SEARCH';
export const FETCH_QUESTIONS_SEARCH_ERROR = 'FETCH_QUESTIONS_SEARCH_ERROR';

export const ADD_QUESTION_DETAILS = 'ADD_QUESTION_DETAILS';
export const LOADING_QUESTION_DETAILS = 'LOADING_QUESTION_DETAILS';
export const CLEAR_QUESTION_DETAILS = 'CLEAR_QUESTION_DETAILS';
export const FETCH_QUESTION_DETAILS_ERROR = 'FETCH_QUESTION_DETAILS_ERROR';

export const ADD_ANSWER_DETAILS = 'ADD_ANSWER_DETAILS';
export const LOADING_ANSWER_DETAILS = 'LOADING_ANSWER_DETAILS';
export const CLEAR_ANSWER_DETAILS = 'CLEAR_ANSWER_DETAILS';
export const FETCH_ANSWER_DETAILS_ERROR = 'FETCH_ANSWER_DETAILS_ERROR';

   