export const SET_ALERT = 'SET_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const SET_TOAST = 'SET_TOAST';
export const CLEAR_TOAST = 'CLEAR_TOAST';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const ADD_QUESTION_DETAILS = 'ADD_QUESTION_DETAILS';
export const LOADING_QUESTION_DETAILS = 'LOADING_QUESTION_DETAILS';
export const CLEAR_QUESTION_DETAILS = 'CLEAR_QUESTION_DETAILS';
export const FETCH_QUESTION_DETAILS_ERROR = 'FETCH_QUESTION_DETAILS_ERROR';